version: 2.1
orbs:
  node: circleci/node@4.1.0
commands:
   setup:
      steps:
        - checkout
        - run: npm ci
jobs:
  lint:
    executor: node/default
    steps:
      - setup
      - run: npm run lint
workflows:
  lint:
    jobs:
      - lint
