jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - run: npm ci
  lint:
    executor: node/default
    steps:
      - run: npm run lint
version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  lint:
    jobs:
      - install
      - lint:
          requires:
            - install
